version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./docker/rails/Dockerfile.prod
    environment:
      RAILS_ENV: 'development'
      DB_HOST: 'db'
    volumes:
      - ./backend:/app
      - bundle_data:/usr/local/bundle
      - /app/vendor
      - /app/tmp
      - /app/log
      # socketファイルの共有
      - sockets:/app/tmp/sockets
    env_file: ./.env
    tty: true
    stdin_open: true
    depends_on:
      - db
    ports:
      - "3333:3333"

  nginx:
    build:
      context: ./backend
      dockerfile: ./docker/nginx/Dockerfile.dev
    ports:
      - "80:80"
    #socketファイルの共有
    volumes:
      - sockets:/app/tmp/sockets
    depends_on:
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    # depends_on:
    #   - backend
  db:
    image: postgres:13.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 'password'
    volumes:
      - postgres_db:/var/lib/postgresql/data

  redis:
    image: redis:5.0.9
    ports:
      - "6378:6379"

volumes:
  postgres_db:
  bundle_data:
  sockets: