version: '3.8'

services:
  db:
    image: postgres:13.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 'password'
    volumes:
      - postgres_db:/var/lib/postgresql/data

  redis:
    image: redis:5.0.9
    ports:
      - "6378:6379"

volumes:
  postgres_db: