require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  Rails:
    Enabled: true
  Include:
    - 'app/**/*.rb'
    - 'spec/**/*.rb'
    - 'lib/**/*.rb'
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
   - 'bin/*'
   - 'db/seeds.rb'
   - 'db/schema.rb'
   - 'vendor/bundle/**/*'

# LineLengthはfalseに設定
Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 80

Metrics/ClassLength:
  Max: 200

Metrics/AbcSize:
  Max: 20
  Exclude:
    - 'lib/tasks/*'

Metrics/CyclomaticComplexity:
  Max: 5

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
  Include:
    - spec/support/*.rb

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false
