# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.3'

gem 'bootsnap', '>= 1.4.2', require: false
gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '~> 4.1'
gem 'rails', '~> 6.0.3', '>= 6.0.3.4'

# json
gem 'active_model_serializers'

# タグとリスト
gem 'acts-as-taggable-on'
gem 'acts_as_list'

# ログイン
gem 'devise_token_auth'

# 環境変数
gem 'dotenv-rails'

# 日本語化
gem 'enum_help'
gem 'rails-i18n'

# redis
gem 'hiredis'
gem 'redis'

# CORS
gem 'rack-cors'

# S3
gem 'aws-sdk-s3', require: false

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'gimei'
  gem 'pry-rails'
  gem 'pry-rescue'
  gem 'rspec-parameterized'
  gem 'rspec-rails'

  # 構文チェック
  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'brakeman', require: false
  gem 'rails_best_practices', require: false
end

group :development do
  gem 'awesome_print'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'bullet'
  gem 'colorize_unpermitted_parameters'
  gem 'listen', '~> 3.2'
  gem 'rails-erd'
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'web-console'
end

group :test do
  gem 'database_cleaner'
  gem 'launchy'
end

gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
